   # LIBRARY MANAGEMENT:

In [2]:
# CREATING NEW DATABASE 'library'
import pymysql
connection = pymysql.connect(host='localhost',user='root',password='Qwerty789*')
my_cursor = connection.cursor()
my_cursor.execute("CREATE DATABASE Library;")
my_cursor.execute("SHOW DATABASES;")
for i in my_cursor:
    print(i)

('final1_db',)
('final_db',)
('information_schema',)
('library',)
('mysql',)
('ninth_may_db',)
('performance_schema',)
('revision_db',)
('sys',)

In [4]:
# CREATING TABLE 'book' inside the DATABASE 'library'
import pymysql
connection = pymysql.connect(host='localhost',user='root',password='Qwerty789*',database = 'library')
my_cursor = connection.cursor()
my_cursor.execute("""CREATE TABLE book(bookid INT,
                           bname VARCHAR(25),
                           author VARCHAR(50),
                           price INT,
                           copy INT,
                           rem_copy INT)
""")
my_cursor.execute("SHOW TABLES;")
for i in my_cursor:
    print(i)

('book',)

In [1]:
# CREATING TABLE 'member' inside the DATABASE 'library'
import pymysql
connection = pymysql.connect(host = 'localhost',user = 'root',password = 'Qwerty789*',database='library')
my_cursor = connection.cursor()
my_cursor.execute("""CREATE TABLE member(memberid INT,
                 mname VARCHAR(50),
                 madd VARCHAR(50),
                 phone INT)""")
my_cursor.execute("SHOW TABLES;")
for i in my_cursor:
    print(i)

('book',)
('member',)

In [6]:
# CREATING TABLE 'issue' inside the DATABASE 'library'
import pymysql
connection = pymysql.connect(host = 'localhost',user = 'root',password = 'Qwerty789*',database='library')
my_cursor = connection.cursor()
my_cursor.execute("""CREATE TABLE issue(issueid INT,
                 issuedate DATE,
                 bookid INT,
                 meemberid INT,
                 copies INT)""")
my_cursor.execute("SHOW TABLES;")
for i in my_cursor:
    print(i)

('book',)
('issue',)
('member',)

In [7]:
# CREATING TABLE 'returns' inside the DATABASE 'library'
import pymysql
connection = pymysql.connect(host = 'localhost',user = 'root',password = 'Qwerty789*',database='library')
my_cursor = connection.cursor()
my_cursor.execute("""CREATE TABLE returns(returnid INT,
                 returndate DATE,
                 bookid INT,
                 meemberid INT,
                 copies INT)""")
my_cursor.execute("SHOW TABLES;")
for i in my_cursor:
    print(i)

('book',)
('issue',)
('member',)
('returns',)

In [10]:
import pymysql
import pandas as pd
connection = pymysql.connect(host='localhost',user='root',password='Qwerty789*',database = 'library')
my_cursor = connection.cursor()
def book_input():
    book_id = int(input('Enter the ID:'))
    book_name = input('Enter the name:')
    author = input('Enter the author:')
    price = int(input('Enter the price:'))
    copies = int(input('Enter the copy:'))
    rem_copy = int(input('Enter the rem_copy:'))
    sql1 = """INSERT INTO book(bookid,bname,author,price,copy,rem_copy)
    VALUES(%s,%s,%s,%s,%s,%s)"""
    mydata = (book_id,book_name,author,price,copies,rem_copy)
    my_cursor.execute(sql1,mydata)
    connection.commit()
    print('Book Added Successfully!')
    
def book_edit():
    x = int(input('Enter the Book_id:',))
    sql2 = "SELECT * FROM book where bookid = {}".format(x)
    my_cursor.execute(sql2)
    r = my_cursor.fetchone()
    if r:
        y = float(input('Enter the new price:'))
        sql3 = "UPDATE book set price ={} where bookid = {}".format(y,x)
        my_cursor.execute(sql3)
        connection.commit()
        print('Price Edited Successfully!')
    else:
        print('Book_Id ERROR!!')
        
def book_delete():
    x = int(input('Enter the Book_id:'))
    sql4 = "SELECT * FROM book where bookid = {}".format(x)
    my_cursor.execute(sql4)
    r = my_cursor.fetchone()
    if r:
        sql5 = "DELETE FROM book where bookid={}".format(x)
        my_cursor.execute(sql5)
        connection.commit()
        print('Book Delted Successfully!') # Book with Id=1 Deleted!
    else:
        print("Book_Id ERROR!!")
        
def book_search():
    x = int(input('Enter the Book_id:'))
    sql5 = "SELECT * FROM book where bookid = {}".format(x)
    my_cursor.execute(sql5)
    r = my_cursor.fetchone()
    if r:
        book_df = pd.read_sql(sql5,connection)
        print(book_df)
    else:
        print('Book_Id ERROR!!')

def member_input():
    member_id = int(input('Enter the ID:'))
    mname = input('Enter the name:')
    madd = input('Enter the address:')
    phone = int(input('Enter the phone_no:')) #(1264, "Out of range value for column 'phone' at row 1")
    sql6 = """INSERT INTO member(memberid,mname,madd,phone)VALUES(%s,%s,%s,%s)"""
    mydata = (member_id,mname,madd,phone)
    my_cursor.execute(sql6,mydata)
    connection.commit()
    print('Member added Successfully!!!')

def member_edit():
    x = int(input('Enter the id:'))
    sql7 = "SELECT* FROM member where memberid = {}".format(x)
    my_cursor.execute(sql7)
    r = my_cursor.fetchone()
    if r:
        y = int(input('Enter the new phone:'))
        sql11 = "UPDATE member set phone = {} where memberid = {}".format(y,x)
        my_cursor.execute(sql11)
        connection.commit()
        print('Edited Successfully!!')
    else:
        print('Member_Id ERROR!!')

def member_delete():
    x = int(input('Enter the id:'))
    sql8 = "SELECT* FROM member where memberid = {}".format(x)
    my_cursor.execute(x)
    r = my_cursor.fetchone()
    if r:
        sql12= "DELETE FROM member where memberid = {}".format(x)
        my_cursor.execute(sql12)
        connection.commit()
        print("Book Deleted Successfully!!")
    else:
        print('Member_Id ERROR!!')
        
def member_search():
    x = int(input('Enter the id:'))
    sql9 = "SELECT* FROM member where memberid = {}".format(x)
    my_cursor.execute(x)
    r = my_cursor.fetchone()
    if r:
        member_df = pd.read_sql(sql9,connection)
        print(member_df)
    else:
        print('Member_Id ERROR!!')
        
def issue_book():
    issue_id = int(input('Enter the ID:'))
    issue_date = input('Enter the Issue_date:')
    book_id = input('Enter the Book_id:')
    member_id = int(input('Enter the member_id:'))
    copies = int(input('Enter the no. of copies:'))
    sql10 = """INSERT INTO issue(issueid,issuedate,bookid,memberid,copies)VALUES(%s,%s,%s,%s,%s)"""
    mydata = (issue_id,issue_date,book_id,member_id,copies)
    my_cursor.execute(sql10,mydata)
    connection.commit()
    print('Book Issued Succcessfully!!')

def return_book():
    return_id = int(input('Enter the return ID:'))
    return_date = input('Enter the return_date:')
    book_id = input('Enter the Book_id:')
    member_id = int(input('Enter the member_id:'))
    copies = int(input('Enter the no. of copies:'))
    sql11 = """INSERT INTO returns(returnid,returndate,bookid,memberid,copies)VALUES(%s,%s,%s,%s,%s)"""
    mydata = (return_id,return_date,book_id,member_id,copies)
    my_cursor.execute(sql11,mydata)
    connection.commit()
    print('Book Returned Succcessfully!!')

def book_details():
    x=int(input("Enter Book ID: "))
    sql12="select*from book where bookid = {}".format(x)
    my_cursor.execute(sql12)
    r=my_cursor.fetchone()
    if r:
        book_details_df = pd.read_sql(sql12,connection)
        print(book_details_df)
    else:
        print('Book_Id ERROR!!')

def member_details():
    x=int(input("Enter Member ID: "))
    sql13="select*from member where memberid = {}".format(x)
    my_cursor.execute(sql13)
    r=my_cursor.fetchone()
    if r:
        members_details_df = pd.read_sql(sql13,connection)
        print(book_details_df)
    else:
        print('Member_Id ERROR!!')
        
def issue_book_details():
    x=int(input("Enter Issue ID: "))
    sql14="select*from issue where issueid = {}".format(x)
    my_cursor.execute(sql14)
    r=my_cursor.fetchone()
    if r:
        issue_details_df = pd.read_sql(sql14,connection)
        print(issue_details_df)
    else:
        print('issue_Id ERROR!!')
        
def return_book_details():
    x=int(input("Enter Return ID: "))
    sql15="select*from returns where returnid = {}".format(x)
    my_cursor.execute(sql15)
    r=my_cursor.fetchone()
    if r:
        return_details_df = pd.read_sql(sql15,connection)
        print(return_details_df)
    else:
        print('Return_Id ERROR!!')
        
def col_chart():

    q= "select bookid, copies from issue" 
    df = pd.read_sql (q,connection)
    plt.bar (df.bookid, df.copies)
    plt.xlabel("BookID") 
    plt.ylabel("Copies Issued")
    plt.title("Best Reading Book")
    plt.xticks(df.bookid)
    plt.show()  
        
    
    
    
    


while True:
    print('''
    Enter your choice!!!
    1. Book Details
    2. Member Details
    3. Transactions
    4. Report
    5. Exit
    ''')
    choice=int(input())
    if choice==1:
        while True:
            print('''
            Enter your choice!!!
            1. Add a Book
            2. Edit a Book
            3. Delete a Book
            4. Search a Book
            5. Return to MAIN MENU
            ''')
            choice=int(input())
            if choice==1:
                book_input()
            elif choice==2:
                book_edit()
            elif choice==3:
                book_delete()
            elif choice==4:
                book_search()
            elif choice==5:
                break
    elif choice==2:
        while True:
            print('''
            Enter your choice!!!
            1. Add a Member
            2. Edit a Member
            3. Delete a Member
            4. Search a Member
            5. Return to MAIN MENU
            ''')
            choice=int(input())
            if choice==1:
                member_input()
            elif choice==2:
                member_edit()
            elif choice==3:
                member_delete()
            elif choice==4:
                member_search()
            elif choice==5:
                break
    elif choice==3:
        while True:
            print('''
            Enter your choice!!!
            1. Issue Book
            2. Return Book
            3. Return to MAIN MENU
            ''')
            choice=int(input())
            if choice==1:
                issue_book()
            elif choice==2:
                return_book()
            elif choice==3:
                break
    elif choice==4:
        while True:
            print('''
            Enter your choice!!!
            1. Book Details
            2. Member Details
            3. Issue Book Details
            4. Return Book Details
            5. Best Reading Book/s(CHART)
            6. Return to MAIN MENU
            ''')
            choice=int(input())
            if choice==1:
                book_details()
            elif choice==2:
                member_details()
            elif choice==3:
                issue_book_details()
            elif choice==4:
                return_book_details()
            elif choice==5:
                col_chart()
            elif choice==6:
                break
    elif choice==5:
        break

    Enter your choice!!!
    1. Book Details
    2. Member Details
    3. Transactions
    4. Report
    5. Exit

4

            Enter your choice!!!
            1. Book Details
            2. Member Details
            3. Issue Book Details
            4. Return Book Details
            5. Best Reading Book/s(CHART)
            6. Return to MAIN MENU

1
Enter Book ID: 3

C:\Users\Home pc\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

   bookid  bname author  price  copy  rem_copy
0       3  Hello    Jha    500    60        12

            Enter your choice!!!
            1. Book Details
            2. Member Details
            3. Issue Book Details
            4. Return Book Details
            5. Best Reading Book/s(CHART)
            6. Return to MAIN MENU

KeyboardInterrupt: Interrupted by user